package com.bloodbridge.enums;

/**
 * Enumeration representing different types of notifications in the system.
 */
public enum NotificationType {
    EMERGENCY_BLOOD_REQUEST,
    DONOR_MATCH_FOUND,
    HOSPITAL_APPROVAL,
    HOSPITAL_REGISTRATION,
    DONATION_SCHEDULED,
    DONATION_REMINDER,
    DONATION_COMPLETED,
    PASSWORD_CHANGED,
    ACCOUNT_ACTIVATED,
    ACCOUNT_DEACTIVATED,
    SYSTEM_ANNOUNCEMENT,
    BLOOD_REQUEST_CREATED,
    REQUEST_VERIFIED,
    REQUEST_REJECTED,
    DONOR_MATCHED,
    DONOR_ACCEPTED,
    DONOR_DECLINED,
    DONOR_REJECTED,
    MATCHED_DONOR,
    DONOR_CONFIRMED,
    FULFILLMENT_STARTED,
    REQUEST_COMPLETED,
    REQUEST_EXPIRED,
    DONATION_ACCEPTED,
    DONATION_CONFIRMED,
    SYSTEM_NOTIFICATION
}
