package com.bloodbridge.enums;

/**
 * Enumeration representing different types of real-time WebSocket events.
 */
public enum RealtimeEventType {
    // Admin & System Level Events
    USER_REGISTERED,
    DONOR_REGISTERED,
    PATIENT_REGISTERED,
    HOSPITAL_REGISTERED,
    HOSPITAL_APPROVED,
    HOSPITAL_REJECTED,
    HOSPITAL_UPDATED,
    USER_DELETED,
    USER_UPDATED,
    ANALYTICS_UPDATED,
    DASHBOARD_STATS_UPDATED,

    // Blood Request & Matching Events
    EMERGENCY_REQUEST_CREATED,
    BLOOD_REQUEST_CREATED,
    BLOOD_REQUEST_VERIFIED,
    BLOOD_REQUEST_REJECTED,
    EMERGENCY_REQUEST_UPDATED,
    BLOOD_REQUEST_UPDATED,
    EMERGENCY_REQUEST_COMPLETED,
    BLOOD_REQUEST_COMPLETED,
    BLOOD_REQUEST_CANCELLED,
    EMERGENCY_REQUEST_ALERT,
    DONOR_MATCHED,

    // Donation Events
    DONOR_ACCEPTED_REQUEST,
    DONOR_ACCEPTED,
    DONOR_REJECTED_REQUEST,
    DONOR_DECLINED,
    DONOR_CONFIRMED,
    FULFILLMENT_STARTED,
    REQUEST_FULFILLED,
    REQUEST_EXPIRED,
    REQUEST_COMPLETED,
    DONATION_CONFIRMED,
    DONATION_COMPLETED,
    DONATION_CANCELLED,

    // Inventory & Health Events
    INVENTORY_UPDATED,
    ELIGIBILITY_CHANGED,

    // Notifications
    NOTIFICATION_CREATED,
    NOTIFICATION_RECEIVED,
    UNREAD_COUNT_CHANGED
}
