package com.bloodbridge.dto.request;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.*;

/**
 * Request DTO for registering or refreshing an FCM device token.
 * Phase 3B.1 — Device Registration.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RegisterDeviceTokenRequest {

    /**
     * The Firebase Cloud Messaging registration token generated by the browser SDK.
     * Required. Must not be blank.
     */
    @NotBlank(message = "FCM token is required")
    @Size(max = 512, message = "FCM token must not exceed 512 characters")
    private String token;

    /**
     * Platform identifier: WEB, ANDROID, IOS.
     * Defaults to WEB if not provided.
     */
    @Builder.Default
    private String platform = "WEB";

    /**
     * Browser name (e.g. Chrome, Firefox, Safari).
     * Parsed by the frontend from navigator.userAgent.
     */
    @Size(max = 50)
    private String browser;

    /**
     * Human-friendly device name (e.g. "John's Laptop").
     * Optional, provided by the client.
     */
    @Size(max = 100)
    private String deviceName;

    /**
     * Stable device fingerprint / client-generated identifier.
     * Optional. Used to correlate sessions across token rotations.
     */
    @Size(max = 200)
    private String deviceId;
}
